services:
  openRMF-Benchmarking:
    build: .
    image: eiu-artc/open-rmf:jazzy-20260622
    tty: true 
    container_name: open-rmf
    network_mode: host
    volumes:
      - ${HOME}/eiu_ws:/home/eiu/rmf_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix

    environment:
      - ENV=development
      - DEBUG=""
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - QT_XCB_GL_INTEGRATION=xcb_glx
      - TURTLEBOT3_MODEL=burger
      - ROS_DOMAIN_ID=1
      - CYCLONEDDS_URI=file:///home/eiu/rmf_ws/cyclonedds_wide.xml

    devices:
      - /dev/dri:/dev/dri

    group_add:
      - video

    privileged: true

  openRMF-vda5050:
    build: .
    image: eiu-artc/open-rmf:jazzy-20260622
    tty: true 
    container_name: vda5050
    network_mode: host

    volumes:
      - ${HOME}/eiu_ws:/home/eiu/rmf_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/dri
    environment:
      - ENV=development
      - DEBUG=""
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - TURTLEBOT3_MODEL=burger
      - ROS_DOMAIN_ID=2

    # security_opt:
    #   - seccomp:unconfined

    # cap_add:
    #   - SYS_ADMIN

    privileged: true
    